#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $KANISHKA_REPO == "JUNGLI-USERBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0NvZGVyWEtyaXNobmEvSlVOR0xJLVVTRVJCT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $KANISHKA_REPO == "JUNGLI-USERBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0NvZGVyWEtyaXNobmEvSlVOR0xJLVVTRVJCT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    elif [[ $KANISHKA_REPO =~ $regex ]]
    then
        if [[ $KANISHKA_REPO_BRANCH ]]
        then
            echo "${KANISHKA_REPO}/archive/${KANISHKA_REPO_BRANCH}.zip"
        else
            echo "${KANISHKA_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0NvZGVyWEtyaXNobmEvSlVOR0xJLVVTRVJCT1QvYXJjaGl2ZS9tYWluLnppcA==" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="JungliBot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    DEADLYPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $DEADLYPATH
    echo "  • Starting Jungli Arank Bot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m JungliBot
}

start_bot
